name: Deploy Veltrix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up PHP & Install Dependencies
        run: |
          cd apps/backend
          composer install --no-dev --optimize-autoloader

      - name: Set Up Node & Install Dependencies
        run: |
          cd apps/frontend
          npm install
          npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install sshpass (for password authentication)
        run: sudo apt-get install -y sshpass

      - name: Deploy via rsync
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude ".github" \
            --exclude ".env" \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/public_html/

      - name: Run Post-Deployment Commands
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USERNAME }}/public_html
            composer install --no-dev --optimize-autoloader
            php spark cache:clear
            php spark migrate
            exit
          EOF
